package org.red5.core.dbModel;
// default package
// Generated Mar 9, 2014 1:16:35 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GcmUserMails generated by hbm2java
 */
@Entity
@Table(name = "gcm_user_mails")
public class GcmUserMails implements java.io.Serializable {

	private Integer id;
	private GcmUsers gcmUsers;
	private String mail;

	public GcmUserMails() {
	}

	public GcmUserMails(GcmUsers gcmUsers, String mail) {
		this.gcmUsers = gcmUsers;
		this.mail = mail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public GcmUsers getGcmUsers() {
		return this.gcmUsers;
	}

	public void setGcmUsers(GcmUsers gcmUsers) {
		this.gcmUsers = gcmUsers;
	}

	@Column(name = "mail",unique = true, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
