package org.red5.core.dbModel;
// default package
// Generated Mar 23, 2014 11:32:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StreamViewers generated by hbm2java
 */
@Entity
@Table(name = "stream_viewers", uniqueConstraints = @UniqueConstraint(columnNames = {
		"streamId", "userId" }))
public class StreamViewers implements java.io.Serializable {

	private Integer id;
	private Streams streams;
	private GcmUsers gcmUsers;

	public StreamViewers() {
	}

	public StreamViewers(Streams streams, GcmUsers gcmUsers) {
		this.streams = streams;
		this.gcmUsers = gcmUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "streamId")
	public Streams getStreams() {
		return this.streams;
	}

	public void setStreams(Streams streams) {
		this.streams = streams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public GcmUsers getGcmUsers() {
		return this.gcmUsers;
	}

	public void setGcmUsers(GcmUsers gcmUsers) {
		this.gcmUsers = gcmUsers;
	}

}
